name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: black lint
        run: |
          python -m pip install black
          black . --check --line-length 120

#      - uses: psf/black@stable
#        with:
#          args: ". --check --line-length 120"
